YEAR="$1"
FILE="$2"
if [ "$DB_NAME" = "" ];then
   DB_NAME="$DB_NAME_PREFIX$YEAR"
fi
TABLE_NAME="candidatos"

case $YEAR in
    2002|2004|2006|2008|2010)
        END_LINE="\r\n"
        ;;
    2012|2014|2016)
        END_LINE="\n"
        ;;
    *)
        END_LINE=""
        ;;
esac

CREATE_DATABASE_CMD="CREATE DATABASE IF NOT EXISTS $DB_NAME;"
echo $CREATE_DATABASE_CMD | mysql -h$DB_HOST -u$DB_USER -p$DB_PASS


case $YEAR in
    2002|2004|2006|2008|2010)
        CREATE_TABLE_CMD=$(cat <<-END
        CREATE TABLE IF NOT EXISTS $TABLE_NAME (
            data_geracao date DEFAULT NULL,
            hora_geracao time DEFAULT NULL,
            ano_eleicao int(11) DEFAULT NULL,
            num_turno int(11) DEFAULT NULL,
            descricao_eleicao varchar(255) CHARACTER SET utf8 DEFAULT NULL,
            sigla_uf varchar(255) CHARACTER SET utf8 DEFAULT NULL,
            sigla_ue varchar(255) CHARACTER SET utf8 DEFAULT NULL,
            descricao_ue varchar(255) CHARACTER SET utf8 DEFAULT NULL,
            codigo_cargo int(11) DEFAULT NULL,
            descricao_cargo varchar(255) CHARACTER SET utf8 DEFAULT NULL,
            nome_candidato varchar(255) CHARACTER SET utf8 DEFAULT NULL,
            sequencial_candidato bigint(11) DEFAULT NULL,
            numero_candidato int(11) DEFAULT NULL,
            cpf_candidato varchar(255) CHARACTER SET utf8 DEFAULT NULL,
            nome_urna_candidato varchar(255) CHARACTER SET utf8 DEFAULT NULL,
            cod_situacao_candidatura int(11) DEFAULT NULL,
            des_situacao_candidatura varchar(255) CHARACTER SET utf8 DEFAULT NULL,
            numero_partido int(11) DEFAULT NULL,
            sigla_partido varchar(255) CHARACTER SET utf8 DEFAULT NULL,
            nome_partido varchar(255) CHARACTER SET utf8 DEFAULT NULL,
            codigo_legenda bigint(11) DEFAULT NULL,
            sigla_legenda varchar(255) CHARACTER SET utf8 DEFAULT NULL,
            composicao_legenda varchar(255) CHARACTER SET utf8 DEFAULT NULL,
            nome_legenda varchar(255) CHARACTER SET utf8 DEFAULT NULL,
            codigo_ocupacao int(11) DEFAULT NULL,
            descricao_ocupacao varchar(255) CHARACTER SET utf8 DEFAULT NULL,
            data_nascimento date DEFAULT NULL,
            num_titulo_eleitoral_candidato varchar(255) CHARACTER SET utf8 DEFAULT NULL,
            idade_data_eleicao int(11) DEFAULT NULL,
            codigo_sexo int(11) DEFAULT NULL,
            descricao_sexo varchar(255) CHARACTER SET utf8 DEFAULT NULL,
            cod_grau_instrucao int(11) DEFAULT NULL,
            descricao_grau_instrucao varchar(255) CHARACTER SET utf8 DEFAULT NULL,
            codigo_estado_civil int(11) DEFAULT NULL,
            descricao_estado_civil varchar(255) CHARACTER SET utf8 DEFAULT NULL,
            codigo_nacionalidade int(11) DEFAULT NULL,
            descricao_nacionalidade varchar(255) CHARACTER SET utf8 DEFAULT NULL,
            sigla_uf_nascimento varchar(255) CHARACTER SET utf8 DEFAULT NULL,
            codigo_municipio_nascimento int(11) DEFAULT NULL,
            nome_municipio_nascimento varchar(255) CHARACTER SET utf8 DEFAULT NULL,
            despesa_max_campanha int(11) DEFAULT NULL,
            cod_sit_tot_turno int(11) DEFAULT NULL,
            desc_sit_tot_turno varchar(255) CHARACTER SET utf8 DEFAULT NULL
        );
END
        )
        ;;

    2012)

        CREATE_TABLE_CMD=$(cat <<-END
        CREATE TABLE IF NOT EXISTS $TABLE_NAME (
            data_geracao date DEFAULT NULL,
            hora_geracao time DEFAULT NULL,
            ano_eleicao int(11) DEFAULT NULL,
            num_turno int(11) DEFAULT NULL,
            descricao_eleicao varchar(255) CHARACTER SET utf8 DEFAULT NULL,
            sigla_uf varchar(255) CHARACTER SET utf8 DEFAULT NULL,
            sigla_ue varchar(255) CHARACTER SET utf8 DEFAULT NULL,
            descricao_ue varchar(255) CHARACTER SET utf8 DEFAULT NULL,
            codigo_cargo int(11) DEFAULT NULL,
            descricao_cargo varchar(255) CHARACTER SET utf8 DEFAULT NULL,
            nome_candidato varchar(255) CHARACTER SET utf8 DEFAULT NULL,
            sequencial_candidato bigint(11) DEFAULT NULL,
            numero_candidato int(11) DEFAULT NULL,
            cpf_candidato varchar(255) CHARACTER SET utf8 DEFAULT NULL,
            nome_urna_candidato varchar(255) CHARACTER SET utf8 DEFAULT NULL,
            cod_situacao_candidatura int(11) DEFAULT NULL,
            des_situacao_candidatura varchar(255) CHARACTER SET utf8 DEFAULT NULL,
            numero_partido int(11) DEFAULT NULL,
            sigla_partido varchar(255) CHARACTER SET utf8 DEFAULT NULL,
            nome_partido varchar(255) CHARACTER SET utf8 DEFAULT NULL,
            codigo_legenda bigint(11) DEFAULT NULL,
            sigla_legenda varchar(255) CHARACTER SET utf8 DEFAULT NULL,
            composicao_legenda varchar(255) CHARACTER SET utf8 DEFAULT NULL,
            nome_legenda varchar(255) CHARACTER SET utf8 DEFAULT NULL,
            codigo_ocupacao int(11) DEFAULT NULL,
            descricao_ocupacao varchar(255) CHARACTER SET utf8 DEFAULT NULL,
            data_nascimento date DEFAULT NULL,
            num_titulo_eleitoral_candidato varchar(255) CHARACTER SET utf8 DEFAULT NULL,
            idade_data_eleicao int(11) DEFAULT NULL,
            codigo_sexo int(11) DEFAULT NULL,
            descricao_sexo varchar(255) CHARACTER SET utf8 DEFAULT NULL,
            cod_grau_instrucao int(11) DEFAULT NULL,
            descricao_grau_instrucao varchar(255) CHARACTER SET utf8 DEFAULT NULL,
            codigo_estado_civil int(11) DEFAULT NULL,
            descricao_estado_civil varchar(255) CHARACTER SET utf8 DEFAULT NULL,
            codigo_nacionalidade int(11) DEFAULT NULL,
            descricao_nacionalidade varchar(255) CHARACTER SET utf8 DEFAULT NULL,
            sigla_uf_nascimento varchar(255) CHARACTER SET utf8 DEFAULT NULL,
            codigo_municipio_nascimento int(11) DEFAULT NULL,
            nome_municipio_nascimento varchar(255) CHARACTER SET utf8 DEFAULT NULL,
            despesa_max_campanha int(11) DEFAULT NULL,
            cod_sit_tot_turno int(11) DEFAULT NULL,
            desc_sit_tot_turno varchar(255) CHARACTER SET utf8 DEFAULT NULL,
            nm_email varchar(255) CHARACTER SET utf8 DEFAULT NULL
        );
END
        )
        ;;

    2014|2016)
        CREATE_TABLE_CMD=$(cat <<-END
        CREATE TABLE IF NOT EXISTS $TABLE_NAME (
            data_geracao date DEFAULT NULL,
            hora_geracao time DEFAULT NULL,
            ano_eleicao int(11) DEFAULT NULL,
            num_turno int(11) DEFAULT NULL,
            descricao_eleicao varchar(255) CHARACTER SET utf8 DEFAULT NULL,
            sigla_uf varchar(255) CHARACTER SET utf8 DEFAULT NULL,
            sigla_ue varchar(255) CHARACTER SET utf8 DEFAULT NULL,
            descricao_ue varchar(255) CHARACTER SET utf8 DEFAULT NULL,
            codigo_cargo int(11) DEFAULT NULL,
            descricao_cargo varchar(255) CHARACTER SET utf8 DEFAULT NULL,
            nome_candidato varchar(255) CHARACTER SET utf8 DEFAULT NULL,
            sequencial_candidato bigint(11) DEFAULT NULL,
            numero_candidato int(11) DEFAULT NULL,
            cpf_candidato varchar(255) CHARACTER SET utf8 DEFAULT NULL,
            nome_urna_candidato varchar(255) CHARACTER SET utf8 DEFAULT NULL,
            cod_situacao_candidatura int(11) DEFAULT NULL,
            des_situacao_candidatura varchar(255) CHARACTER SET utf8 DEFAULT NULL,
            numero_partido int(11) DEFAULT NULL,
            sigla_partido varchar(255) CHARACTER SET utf8 DEFAULT NULL,
            nome_partido varchar(255) CHARACTER SET utf8 DEFAULT NULL,
            codigo_legenda bigint(11) DEFAULT NULL,
            sigla_legenda varchar(255) CHARACTER SET utf8 DEFAULT NULL,
            composicao_legenda varchar(255) CHARACTER SET utf8 DEFAULT NULL,
            nome_legenda varchar(255) CHARACTER SET utf8 DEFAULT NULL,
            codigo_ocupacao int(11) DEFAULT NULL,
            descricao_ocupacao varchar(255) CHARACTER SET utf8 DEFAULT NULL,
            data_nascimento date DEFAULT NULL,
            num_titulo_eleitoral_candidato varchar(255) CHARACTER SET utf8 DEFAULT NULL,
            idade_data_eleicao int(11) DEFAULT NULL,
            codigo_sexo int(11) DEFAULT NULL,
            descricao_sexo varchar(255) CHARACTER SET utf8 DEFAULT NULL,
            cod_grau_instrucao int(11) DEFAULT NULL,
            descricao_grau_instrucao varchar(255) CHARACTER SET utf8 DEFAULT NULL,
            codigo_estado_civil int(11) DEFAULT NULL,
            descricao_estado_civil varchar(255) CHARACTER SET utf8 DEFAULT NULL,
            codigo_cor_raca varchar(255) CHARACTER SET utf8 DEFAULT NULL,
            descricao_cor_raca varchar(255) CHARACTER SET utf8 DEFAULT NULL,
            codigo_nacionalidade int(11) DEFAULT NULL,
            descricao_nacionalidade varchar(255) CHARACTER SET utf8 DEFAULT NULL,
            sigla_uf_nascimento varchar(255) CHARACTER SET utf8 DEFAULT NULL,
            codigo_municipio_nascimento int(11) DEFAULT NULL,
            nome_municipio_nascimento varchar(255) CHARACTER SET utf8 DEFAULT NULL,
            despesa_max_campanha int(11) DEFAULT NULL,
            cod_sit_tot_turno int(11) DEFAULT NULL,
            desc_sit_tot_turno varchar(255) CHARACTER SET utf8 DEFAULT NULL,
            nm_email varchar(255) CHARACTER SET utf8 DEFAULT NULL
        );
END
        )
        ;;
    *)
        CREATE_TABLE_CMD=""
        ;;
esac
echo $CREATE_TABLE_CMD | mysql -h$DB_HOST -u$DB_USER -p$DB_PASS $DB_NAME

case $YEAR in
    2002|2004)

        LOAD_DATA_CMD=$(cat <<-END
        load data local infile "$FILE"
          into table $TABLE_NAME
            fields terminated by ';' OPTIONALLY ENCLOSED BY '"'
            lines terminated by "$END_LINE"
            (@data_geracao,
             @hora_geracao,
             @ano_eleicao,
             @num_turno,
             @descricao_eleicao,
             @sigla_uf,
             @sigla_ue,
             @descricao_ue,
             @codigo_cargo,
             @descricao_cargo,
             @nome_candidato,
             @sequencial_candidato,
             @numero_candidato,
             @cpf_candidato,
             @nome_urna_candidato,
             @cod_situacao_candidatura,
             @des_situacao_candidatura,
             @numero_partido,
             @sigla_partido,
             @nome_partido,
             @codigo_legenda,
             @sigla_legenda,
             @composicao_legenda,
             @nome_legenda,
             @codigo_ocupacao,
             @descricao_ocupacao,
             @data_nascimento,
             @num_titulo_eleitoral_candidato,
             @idade_data_eleicao,
             @codigo_sexo,
             @descricao_sexo,
             @cod_grau_instrucao,
             @descricao_grau_instrucao,
             @codigo_estado_civil,
             @descricao_estado_civil,
             @codigo_nacionalidade,
             @descricao_nacionalidade,
             @sigla_uf_nascimento,
             @codigo_municipio_nascimento,
             @nome_municipio_nascimento,
             @despesa_max_campanha,
             @cod_sit_tot_turno,
             @desc_sit_tot_turno)
        SET
            data_geracao=STR_TO_DATE(NULLIF(TRIM(@data_geracao), ""), "%d/%m/%Y"),
            hora_geracao=STR_TO_DATE(NULLIF(TRIM(@hora_geracao), ""), "%H:%i:%s"),
            ano_eleicao=NULLIF(@ano_eleicao, ""),
            num_turno=NULLIF(@num_turno, ""),
            descricao_eleicao=NULLIF(TRIM(@descricao_eleicao), ""),
            sigla_uf=NULLIF(TRIM(@sigla_uf), ""),
            sigla_ue=NULLIF(TRIM(@sigla_ue), ""),
            descricao_ue=NULLIF(TRIM(@descricao_ue), ""),
            codigo_cargo=NULLIF(@codigo_cargo, ""),
            descricao_cargo=NULLIF(TRIM(@descricao_cargo), ""),
            nome_candidato=NULLIF(TRIM(@nome_candidato), ""),
            sequencial_candidato=NULLIF(@sequencial_candidato, ""),
            numero_candidato=NULLIF(@numero_candidato, ""),
            cpf_candidato=NULLIF(TRIM(@cpf_candidato), ""),
            nome_urna_candidato=NULLIF(TRIM(@nome_urna_candidato), ""),
            cod_situacao_candidatura=NULLIF(@cod_situacao_candidatura, ""),
            des_situacao_candidatura=NULLIF(TRIM(@des_situacao_candidatura), ""),
            numero_partido=NULLIF(@numero_partido, ""),
            sigla_partido=NULLIF(TRIM(@sigla_partido), ""),
            nome_partido=NULLIF(TRIM(@nome_partido), ""),
            codigo_legenda=IF(@codigo_legenda="" OR @codigo_legenda=-1 OR @codigo_legenda=-3, null, @codigo_legenda),
            sigla_legenda=NULLIF(TRIM(@sigla_legenda), ""),
            composicao_legenda=NULLIF(TRIM(@composicao_legenda), ""),
            nome_legenda=NULLIF(TRIM(@nome_legenda), ""),
            codigo_ocupacao=NULLIF(@codigo_ocupacao, ""),
            descricao_ocupacao=NULLIF(TRIM(@descricao_ocupacao), ""),
            data_nascimento=STR_TO_DATE(NULLIF(TRIM(@data_nascimento), ""), "%d%m%Y"),
            num_titulo_eleitoral_candidato=NULLIF(TRIM(@num_titulo_eleitoral_candidato), ""),
            idade_data_eleicao=IF(@idade_data_eleicao="" OR @idade_data_eleicao=-1 OR @idade_data_eleicao=-3, null, @idade_data_eleicao),
            codigo_sexo=NULLIF(@codigo_sexo, ""),
            descricao_sexo=NULLIF(TRIM(@descricao_sexo), ""),
            cod_grau_instrucao=NULLIF(@cod_grau_instrucao, ""),
            descricao_grau_instrucao=NULLIF(TRIM(@descricao_grau_instrucao), ""),
            codigo_estado_civil=NULLIF(@codigo_estado_civil, ""),
            descricao_estado_civil=NULLIF(TRIM(@descricao_estado_civil), ""),
            codigo_nacionalidade=NULLIF(@codigo_nacionalidade, ""),
            descricao_nacionalidade=NULLIF(TRIM(@descricao_nacionalidade), ""),
            sigla_uf_nascimento=NULLIF(TRIM(@sigla_uf_nascimento), ""),
            codigo_municipio_nascimento=IF(@codigo_municipio_nascimento="" OR @codigo_municipio_nascimento=-1 OR @codigo_municipio_nascimento=-3, null, @codigo_municipio_nascimento),
            nome_municipio_nascimento=NULLIF(TRIM(@nome_municipio_nascimento), ""),
            despesa_max_campanha=IF(@despesa_max_campanha="" OR @despesa_max_campanha=-1 OR @despesa_max_campanha=-3, null, @despesa_max_campanha),
            cod_sit_tot_turno=IF(@cod_sit_tot_turno="" OR @cod_sit_tot_turno=-1 OR @cod_sit_tot_turno=-3, null, @cod_sit_tot_turno),
            desc_sit_tot_turno=NULLIF(TRIM(@desc_sit_tot_turno), "");
END
        )
        ;;

    2006)

        LOAD_DATA_CMD=$(cat <<-END
        load data local infile "$FILE"
          into table $TABLE_NAME
            fields terminated by ';' OPTIONALLY ENCLOSED BY '"'
            lines terminated by "$END_LINE"
            (@data_geracao,
             @hora_geracao,
             @ano_eleicao,
             @num_turno,
             @descricao_eleicao,
             @sigla_uf,
             @sigla_ue,
             @descricao_ue,
             @codigo_cargo,
             @descricao_cargo,
             @nome_candidato,
             @sequencial_candidato,
             @numero_candidato,
             @cpf_candidato,
             @nome_urna_candidato,
             @cod_situacao_candidatura,
             @des_situacao_candidatura,
             @numero_partido,
             @sigla_partido,
             @nome_partido,
             @codigo_legenda,
             @sigla_legenda,
             @composicao_legenda,
             @nome_legenda,
             @codigo_ocupacao,
             @descricao_ocupacao,
             @data_nascimento,
             @num_titulo_eleitoral_candidato,
             @idade_data_eleicao,
             @codigo_sexo,
             @descricao_sexo,
             @cod_grau_instrucao,
             @descricao_grau_instrucao,
             @codigo_estado_civil,
             @descricao_estado_civil,
             @codigo_nacionalidade,
             @descricao_nacionalidade,
             @sigla_uf_nascimento,
             @codigo_municipio_nascimento,
             @nome_municipio_nascimento,
             @despesa_max_campanha,
             @cod_sit_tot_turno,
             @desc_sit_tot_turno)
        SET
            data_geracao=STR_TO_DATE(NULLIF(TRIM(@data_geracao), ""), "%d/%m/%Y"),
            hora_geracao=STR_TO_DATE(NULLIF(TRIM(@hora_geracao), ""), "%H:%i:%s"),
            ano_eleicao=NULLIF(@ano_eleicao, ""),
            num_turno=NULLIF(@num_turno, ""),
            descricao_eleicao=NULLIF(TRIM(@descricao_eleicao), ""),
            sigla_uf=NULLIF(TRIM(@sigla_uf), ""),
            sigla_ue=NULLIF(TRIM(@sigla_ue), ""),
            descricao_ue=NULLIF(TRIM(@descricao_ue), ""),
            codigo_cargo=NULLIF(@codigo_cargo, ""),
            descricao_cargo=NULLIF(TRIM(@descricao_cargo), ""),
            nome_candidato=NULLIF(TRIM(@nome_candidato), ""),
            sequencial_candidato=NULLIF(@sequencial_candidato, ""),
            numero_candidato=NULLIF(@numero_candidato, ""),
            cpf_candidato=NULLIF(TRIM(@cpf_candidato), ""),
            nome_urna_candidato=NULLIF(TRIM(@nome_urna_candidato), ""),
            cod_situacao_candidatura=NULLIF(@cod_situacao_candidatura, ""),
            des_situacao_candidatura=NULLIF(TRIM(@des_situacao_candidatura), ""),
            numero_partido=NULLIF(@numero_partido, ""),
            sigla_partido=NULLIF(TRIM(@sigla_partido), ""),
            nome_partido=NULLIF(TRIM(@nome_partido), ""),
            codigo_legenda=IF(@codigo_legenda="" OR @codigo_legenda=-1 OR @codigo_legenda=-3, null, @codigo_legenda),
            sigla_legenda=NULLIF(TRIM(@sigla_legenda), ""),
            composicao_legenda=NULLIF(TRIM(@composicao_legenda), ""),
            nome_legenda=NULLIF(TRIM(@nome_legenda), ""),
            codigo_ocupacao=NULLIF(@codigo_ocupacao, ""),
            descricao_ocupacao=NULLIF(TRIM(@descricao_ocupacao), ""),
            data_nascimento=STR_TO_DATE(NULLIF(TRIM(@data_nascimento), ""), "%d/%m/%Y"),
            num_titulo_eleitoral_candidato=NULLIF(TRIM(@num_titulo_eleitoral_candidato), ""),
            idade_data_eleicao=IF(@idade_data_eleicao="" OR @idade_data_eleicao=-1 OR @idade_data_eleicao=-3, null, @idade_data_eleicao),
            codigo_sexo=NULLIF(@codigo_sexo, ""),
            descricao_sexo=NULLIF(TRIM(@descricao_sexo), ""),
            cod_grau_instrucao=NULLIF(@cod_grau_instrucao, ""),
            descricao_grau_instrucao=NULLIF(TRIM(@descricao_grau_instrucao), ""),
            codigo_estado_civil=NULLIF(@codigo_estado_civil, ""),
            descricao_estado_civil=NULLIF(TRIM(@descricao_estado_civil), ""),
            codigo_nacionalidade=NULLIF(@codigo_nacionalidade, ""),
            descricao_nacionalidade=NULLIF(TRIM(@descricao_nacionalidade), ""),
            sigla_uf_nascimento=NULLIF(TRIM(@sigla_uf_nascimento), ""),
            codigo_municipio_nascimento=IF(@codigo_municipio_nascimento="" OR @codigo_municipio_nascimento=-1 OR @codigo_municipio_nascimento=-3, null, @codigo_municipio_nascimento),
            nome_municipio_nascimento=NULLIF(TRIM(@nome_municipio_nascimento), ""),
            despesa_max_campanha=IF(@despesa_max_campanha="" OR @despesa_max_campanha=-1 OR @despesa_max_campanha=-3, null, @despesa_max_campanha),
            cod_sit_tot_turno=IF(@cod_sit_tot_turno="" OR @cod_sit_tot_turno=-1 OR @cod_sit_tot_turno=-3, null, @cod_sit_tot_turno),
            desc_sit_tot_turno=NULLIF(TRIM(@desc_sit_tot_turno), "");
END
        )
        ;;

    2008|2010)

        LOAD_DATA_CMD=$(cat <<-END
        load data local infile "$FILE"
          into table $TABLE_NAME
            fields terminated by ';' OPTIONALLY ENCLOSED BY '"'
            lines terminated by "$END_LINE"
            (@data_geracao,
             @hora_geracao,
             @ano_eleicao,
             @num_turno,
             @descricao_eleicao,
             @sigla_uf,
             @sigla_ue,
             @descricao_ue,
             @codigo_cargo,
             @descricao_cargo,
             @nome_candidato,
             @sequencial_candidato,
             @numero_candidato,
             @cpf_candidato,
             @nome_urna_candidato,
             @cod_situacao_candidatura,
             @des_situacao_candidatura,
             @numero_partido,
             @sigla_partido,
             @nome_partido,
             @codigo_legenda,
             @sigla_legenda,
             @composicao_legenda,
             @nome_legenda,
             @codigo_ocupacao,
             @descricao_ocupacao,
             @data_nascimento,
             @num_titulo_eleitoral_candidato,
             @idade_data_eleicao,
             @codigo_sexo,
             @descricao_sexo,
             @cod_grau_instrucao,
             @descricao_grau_instrucao,
             @codigo_estado_civil,
             @descricao_estado_civil,
             @codigo_nacionalidade,
             @descricao_nacionalidade,
             @sigla_uf_nascimento,
             @codigo_municipio_nascimento,
             @nome_municipio_nascimento,
             @despesa_max_campanha,
             @cod_sit_tot_turno,
             @desc_sit_tot_turno)
        SET
            data_geracao=STR_TO_DATE(NULLIF(TRIM(@data_geracao), ""), "%d/%m/%Y"),
            hora_geracao=STR_TO_DATE(NULLIF(TRIM(@hora_geracao), ""), "%H:%i:%s"),
            ano_eleicao=NULLIF(@ano_eleicao, ""),
            num_turno=NULLIF(@num_turno, ""),
            descricao_eleicao=NULLIF(TRIM(@descricao_eleicao), ""),
            sigla_uf=NULLIF(TRIM(@sigla_uf), ""),
            sigla_ue=NULLIF(TRIM(@sigla_ue), ""),
            descricao_ue=NULLIF(TRIM(@descricao_ue), ""),
            codigo_cargo=NULLIF(@codigo_cargo, ""),
            descricao_cargo=NULLIF(TRIM(@descricao_cargo), ""),
            nome_candidato=NULLIF(TRIM(@nome_candidato), ""),
            sequencial_candidato=NULLIF(@sequencial_candidato, ""),
            numero_candidato=NULLIF(@numero_candidato, ""),
            cpf_candidato=NULLIF(TRIM(@cpf_candidato), ""),
            nome_urna_candidato=NULLIF(TRIM(@nome_urna_candidato), ""),
            cod_situacao_candidatura=NULLIF(@cod_situacao_candidatura, ""),
            des_situacao_candidatura=NULLIF(TRIM(@des_situacao_candidatura), ""),
            numero_partido=NULLIF(@numero_partido, ""),
            sigla_partido=NULLIF(TRIM(@sigla_partido), ""),
            nome_partido=NULLIF(TRIM(@nome_partido), ""),
            codigo_legenda=IF(@codigo_legenda="" OR @codigo_legenda=-1 OR @codigo_legenda=-3, null, @codigo_legenda),
            sigla_legenda=NULLIF(TRIM(@sigla_legenda), ""),
            composicao_legenda=NULLIF(TRIM(@composicao_legenda), ""),
            nome_legenda=NULLIF(TRIM(@nome_legenda), ""),
            codigo_ocupacao=NULLIF(@codigo_ocupacao, ""),
            descricao_ocupacao=NULLIF(TRIM(@descricao_ocupacao), ""),
            data_nascimento=STR_TO_DATE(NULLIF(TRIM(@data_nascimento), ""), "%d-%M-%y"),
            num_titulo_eleitoral_candidato=NULLIF(TRIM(@num_titulo_eleitoral_candidato), ""),
            idade_data_eleicao=IF(@idade_data_eleicao="" OR @idade_data_eleicao=-1 OR @idade_data_eleicao=-3, null, @idade_data_eleicao),
            codigo_sexo=NULLIF(@codigo_sexo, ""),
            descricao_sexo=NULLIF(TRIM(@descricao_sexo), ""),
            cod_grau_instrucao=NULLIF(@cod_grau_instrucao, ""),
            descricao_grau_instrucao=NULLIF(TRIM(@descricao_grau_instrucao), ""),
            codigo_estado_civil=NULLIF(@codigo_estado_civil, ""),
            descricao_estado_civil=NULLIF(TRIM(@descricao_estado_civil), ""),
            codigo_nacionalidade=NULLIF(@codigo_nacionalidade, ""),
            descricao_nacionalidade=NULLIF(TRIM(@descricao_nacionalidade), ""),
            sigla_uf_nascimento=NULLIF(TRIM(@sigla_uf_nascimento), ""),
            codigo_municipio_nascimento=IF(@codigo_municipio_nascimento="" OR @codigo_municipio_nascimento=-1 OR @codigo_municipio_nascimento=-3, null, @codigo_municipio_nascimento),
            nome_municipio_nascimento=NULLIF(TRIM(@nome_municipio_nascimento), ""),
            despesa_max_campanha=IF(@despesa_max_campanha="" OR @despesa_max_campanha=-1 OR @despesa_max_campanha=-3, null, @despesa_max_campanha),
            cod_sit_tot_turno=IF(@cod_sit_tot_turno="" OR @cod_sit_tot_turno=-1 OR @cod_sit_tot_turno=-3, null, @cod_sit_tot_turno),
            desc_sit_tot_turno=NULLIF(TRIM(@desc_sit_tot_turno), "");
END
        )
        ;;

    2012)

        LOAD_DATA_CMD=$(cat <<-END
        load data local infile "$FILE"
          into table $TABLE_NAME
            fields terminated by ';' OPTIONALLY ENCLOSED BY '"'
            lines terminated by "$END_LINE"
            (@data_geracao,
             @hora_geracao,
             @ano_eleicao,
             @num_turno,
             @descricao_eleicao,
             @sigla_uf,
             @sigla_ue,
             @descricao_ue,
             @codigo_cargo,
             @descricao_cargo,
             @nome_candidato,
             @sequencial_candidato,
             @numero_candidato,
             @cpf_candidato,
             @nome_urna_candidato,
             @cod_situacao_candidatura,
             @des_situacao_candidatura,
             @numero_partido,
             @sigla_partido,
             @nome_partido,
             @codigo_legenda,
             @sigla_legenda,
             @composicao_legenda,
             @nome_legenda,
             @codigo_ocupacao,
             @descricao_ocupacao,
             @data_nascimento,
             @num_titulo_eleitoral_candidato,
             @idade_data_eleicao,
             @codigo_sexo,
             @descricao_sexo,
             @cod_grau_instrucao,
             @descricao_grau_instrucao,
             @codigo_estado_civil,
             @descricao_estado_civil,
             @codigo_nacionalidade,
             @descricao_nacionalidade,
             @sigla_uf_nascimento,
             @codigo_municipio_nascimento,
             @nome_municipio_nascimento,
             @despesa_max_campanha,
             @cod_sit_tot_turno,
             @desc_sit_tot_turno,
             @nm_email)
        SET
            data_geracao=STR_TO_DATE(NULLIF(TRIM(@data_geracao), ""), "%d/%m/%Y"),
            hora_geracao=STR_TO_DATE(NULLIF(TRIM(@hora_geracao), ""), "%H:%i:%s"),
            ano_eleicao=NULLIF(@ano_eleicao, ""),
            num_turno=NULLIF(@num_turno, ""),
            descricao_eleicao=NULLIF(TRIM(@descricao_eleicao), ""),
            sigla_uf=NULLIF(TRIM(@sigla_uf), ""),
            sigla_ue=NULLIF(TRIM(@sigla_ue), ""),
            descricao_ue=NULLIF(TRIM(@descricao_ue), ""),
            codigo_cargo=NULLIF(@codigo_cargo, ""),
            descricao_cargo=NULLIF(TRIM(@descricao_cargo), ""),
            nome_candidato=NULLIF(TRIM(@nome_candidato), ""),
            sequencial_candidato=NULLIF(@sequencial_candidato, ""),
            numero_candidato=NULLIF(@numero_candidato, ""),
            cpf_candidato=NULLIF(TRIM(@cpf_candidato), ""),
            nome_urna_candidato=NULLIF(TRIM(@nome_urna_candidato), ""),
            cod_situacao_candidatura=NULLIF(@cod_situacao_candidatura, ""),
            des_situacao_candidatura=NULLIF(TRIM(@des_situacao_candidatura), ""),
            numero_partido=NULLIF(@numero_partido, ""),
            sigla_partido=NULLIF(TRIM(@sigla_partido), ""),
            nome_partido=NULLIF(TRIM(@nome_partido), ""),
            codigo_legenda=IF(@codigo_legenda="" OR @codigo_legenda=-1 OR @codigo_legenda=-3, null, @codigo_legenda),
            sigla_legenda=NULLIF(TRIM(@sigla_legenda), ""),
            composicao_legenda=NULLIF(TRIM(@composicao_legenda), ""),
            nome_legenda=NULLIF(TRIM(@nome_legenda), ""),
            codigo_ocupacao=NULLIF(@codigo_ocupacao, ""),
            descricao_ocupacao=NULLIF(TRIM(@descricao_ocupacao), ""),
            data_nascimento=STR_TO_DATE(NULLIF(TRIM(@data_nascimento), ""), "%d/%m/%Y"),
            num_titulo_eleitoral_candidato=NULLIF(TRIM(@num_titulo_eleitoral_candidato), ""),
            idade_data_eleicao=IF(@idade_data_eleicao="" OR @idade_data_eleicao=-1 OR @idade_data_eleicao=-3, null, @idade_data_eleicao),
            codigo_sexo=NULLIF(@codigo_sexo, ""),
            descricao_sexo=NULLIF(TRIM(@descricao_sexo), ""),
            cod_grau_instrucao=NULLIF(@cod_grau_instrucao, ""),
            descricao_grau_instrucao=NULLIF(TRIM(@descricao_grau_instrucao), ""),
            codigo_estado_civil=NULLIF(@codigo_estado_civil, ""),
            descricao_estado_civil=NULLIF(TRIM(@descricao_estado_civil), ""),
            codigo_nacionalidade=NULLIF(@codigo_nacionalidade, ""),
            descricao_nacionalidade=NULLIF(TRIM(@descricao_nacionalidade), ""),
            sigla_uf_nascimento=NULLIF(TRIM(@sigla_uf_nascimento), ""),
            codigo_municipio_nascimento=IF(@codigo_municipio_nascimento="" OR @codigo_municipio_nascimento=-1 OR @codigo_municipio_nascimento=-3, null, @codigo_municipio_nascimento),
            nome_municipio_nascimento=NULLIF(TRIM(@nome_municipio_nascimento), ""),
            despesa_max_campanha=IF(@despesa_max_campanha="" OR @despesa_max_campanha=-1 OR @despesa_max_campanha=-3, null, @despesa_max_campanha),
            cod_sit_tot_turno=IF(@cod_sit_tot_turno="" OR @cod_sit_tot_turno=-1 OR @cod_sit_tot_turno=-3, null, @cod_sit_tot_turno),
            desc_sit_tot_turno=NULLIF(TRIM(@desc_sit_tot_turno), ""),
            nm_email=NULLIF(TRIM(@nm_email), "");
END
        )
        ;;

    2014|2016)
        LOAD_DATA_CMD=$(cat <<-END
        load data local infile "$FILE"
          into table $TABLE_NAME
            fields terminated by ';' OPTIONALLY ENCLOSED BY '"'
            lines terminated by "$END_LINE"
            (@data_geracao,
             @hora_geracao,
             @ano_eleicao,
             @num_turno,
             @descricao_eleicao,
             @sigla_uf,
             @sigla_ue,
             @descricao_ue,
             @codigo_cargo,
             @descricao_cargo,
             @nome_candidato,
             @sequencial_candidato,
             @numero_candidato,
             @cpf_candidato,
             @nome_urna_candidato,
             @cod_situacao_candidatura,
             @des_situacao_candidatura,
             @numero_partido,
             @sigla_partido,
             @nome_partido,
             @codigo_legenda,
             @sigla_legenda,
             @composicao_legenda,
             @nome_legenda,
             @codigo_ocupacao,
             @descricao_ocupacao,
             @data_nascimento,
             @num_titulo_eleitoral_candidato,
             @idade_data_eleicao,
             @codigo_sexo,
             @descricao_sexo,
             @cod_grau_instrucao,
             @descricao_grau_instrucao,
             @codigo_estado_civil,
             @descricao_estado_civil,
             @codigo_cor_raca,
             @descricao_cor_raca,
             @codigo_nacionalidade,
             @descricao_nacionalidade,
             @sigla_uf_nascimento,
             @codigo_municipio_nascimento,
             @nome_municipio_nascimento,
             @despesa_max_campanha,
             @cod_sit_tot_turno,
             @desc_sit_tot_turno,
             @nm_email)
        SET
            data_geracao=STR_TO_DATE(NULLIF(TRIM(@data_geracao), ""), "%d/%m/%Y"),
            hora_geracao=STR_TO_DATE(NULLIF(TRIM(@hora_geracao), ""), "%H:%i:%s"),
            ano_eleicao=NULLIF(@ano_eleicao, ""),
            num_turno=NULLIF(@num_turno, ""),
            descricao_eleicao=NULLIF(TRIM(@descricao_eleicao), ""),
            sigla_uf=NULLIF(TRIM(@sigla_uf), ""),
            sigla_ue=NULLIF(TRIM(@sigla_ue), ""),
            descricao_ue=NULLIF(TRIM(@descricao_ue), ""),
            codigo_cargo=NULLIF(@codigo_cargo, ""),
            descricao_cargo=NULLIF(TRIM(@descricao_cargo), ""),
            nome_candidato=NULLIF(TRIM(@nome_candidato), ""),
            sequencial_candidato=NULLIF(@sequencial_candidato, ""),
            numero_candidato=NULLIF(@numero_candidato, ""),
            cpf_candidato=NULLIF(TRIM(@cpf_candidato), ""),
            nome_urna_candidato=NULLIF(TRIM(@nome_urna_candidato), ""),
            cod_situacao_candidatura=NULLIF(@cod_situacao_candidatura, ""),
            des_situacao_candidatura=NULLIF(TRIM(@des_situacao_candidatura), ""),
            numero_partido=NULLIF(@numero_partido, ""),
            sigla_partido=NULLIF(TRIM(@sigla_partido), ""),
            nome_partido=NULLIF(TRIM(@nome_partido), ""),
            codigo_legenda=IF(@codigo_legenda="" OR @codigo_legenda=-1 OR @codigo_legenda=-3, null, @codigo_legenda),
            sigla_legenda=NULLIF(TRIM(@sigla_legenda), ""),
            composicao_legenda=NULLIF(TRIM(@composicao_legenda), ""),
            nome_legenda=NULLIF(TRIM(@nome_legenda), ""),
            codigo_ocupacao=NULLIF(@codigo_ocupacao, ""),
            descricao_ocupacao=NULLIF(TRIM(@descricao_ocupacao), ""),
            data_nascimento=STR_TO_DATE(NULLIF(TRIM(@data_nascimento), ""), "%d/%m/%Y"),
            num_titulo_eleitoral_candidato=NULLIF(TRIM(@num_titulo_eleitoral_candidato), ""),
            idade_data_eleicao=IF(@idade_data_eleicao="" OR @idade_data_eleicao=-1 OR @idade_data_eleicao=-3, null, @idade_data_eleicao),
            codigo_sexo=NULLIF(@codigo_sexo, ""),
            descricao_sexo=NULLIF(TRIM(@descricao_sexo), ""),
            cod_grau_instrucao=NULLIF(@cod_grau_instrucao, ""),
            descricao_grau_instrucao=NULLIF(TRIM(@descricao_grau_instrucao), ""),
            codigo_estado_civil=NULLIF(@codigo_estado_civil, ""),
            descricao_estado_civil=NULLIF(TRIM(@descricao_estado_civil), ""),
            codigo_cor_raca=NULLIF(TRIM(@codigo_cor_raca), ""),
            descricao_cor_raca=NULLIF(TRIM(@descricao_cor_raca), ""),
            codigo_nacionalidade=NULLIF(@codigo_nacionalidade, ""),
            descricao_nacionalidade=NULLIF(TRIM(@descricao_nacionalidade), ""),
            sigla_uf_nascimento=NULLIF(TRIM(@sigla_uf_nascimento), ""),
            codigo_municipio_nascimento=IF(@codigo_municipio_nascimento="" OR @codigo_municipio_nascimento=-1 OR @codigo_municipio_nascimento=-3, null, @codigo_municipio_nascimento),
            nome_municipio_nascimento=NULLIF(TRIM(@nome_municipio_nascimento), ""),
            despesa_max_campanha=IF(@despesa_max_campanha="" OR @despesa_max_campanha=-1 OR @despesa_max_campanha=-3, null, @despesa_max_campanha),
            cod_sit_tot_turno=IF(@cod_sit_tot_turno="" OR @cod_sit_tot_turno=-1 OR @cod_sit_tot_turno=-3, null, @cod_sit_tot_turno),
            desc_sit_tot_turno=NULLIF(TRIM(@desc_sit_tot_turno), ""),
            nm_email=NULLIF(TRIM(@nm_email), "");
END
        )
        ;;

    *)
        LOAD_DATA_CMD=""
        ;;
esac
echo $LOAD_DATA_CMD | mysql -h$DB_HOST -u$DB_USER -p$DB_PASS $DB_NAME

exit 0
